name: 'Download GGUF'
on:
  workflow_dispatch:
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download the GGUF file
        run: |
          wget --progress=bar:force -O model.gguf "https://huggingface.co/bartowski/DarkIdol-Llama-3.1-8B-Instruct-1.2-Uncensored-GGUF/blob/main/DarkIdol-Llama-3.1-8B-Instruct-1.2-Uncensored-Q6_K_L.gguf"
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-file
          path: model.gguf
          retention-days: 1
